"""Static sector/industry for tickers in this app when Yahoo .info is blocked (serverless).

Market cap is filled separately via yfinance fast_info in stock_service.
"""

from __future__ import annotations


def _p(sector: str, industry: str | None = None) -> tuple[str, str]:
    return (sector, industry or sector)


# Korean listings — English sector labels (GICS-style) for UI consistency
_KR: dict[str, tuple[str, str]] = {
    "005930.KS": _p("Technology", "Semiconductors"),
    "000660.KS": _p("Technology", "Semiconductors"),
    "373220.KS": _p("Industrials", "Electrical Equipment"),
    "207940.KS": _p("Healthcare", "Biotechnology"),
    "006400.KS": _p("Technology", "Electrical Equipment"),
    "005380.KS": _p("Consumer Cyclical", "Auto Manufacturers"),
    "051910.KS": _p("Basic Materials", "Chemicals"),
    "000270.KS": _p("Consumer Cyclical", "Auto Manufacturers"),
    "068270.KS": _p("Healthcare", "Biotechnology"),
    "035420.KS": _p("Communication Services", "Internet Content"),
    "035720.KS": _p("Communication Services", "Internet Content"),
    "005490.KS": _p("Basic Materials", "Steel"),
    "028260.KS": _p("Industrials", "Construction & Engineering"),
    "012450.KS": _p("Industrials", "Aerospace & Defense"),
    "055550.KS": _p("Financial Services", "Banks"),
    "105560.KS": _p("Financial Services", "Banks"),
    "017670.KS": _p("Communication Services", "Telecom"),
    "032830.KS": _p("Financial Services", "Insurance"),
    "066570.KS": _p("Technology", "Consumer Electronics"),
    "003670.KS": _p("Basic Materials", "Specialty Chemicals"),
    "034020.KS": _p("Industrials", "Heavy Machinery"),
    "030200.KS": _p("Communication Services", "Telecom"),
    "012330.KS": _p("Consumer Cyclical", "Auto Parts"),
    "259960.KS": _p("Communication Services", "Electronic Gaming"),
    "352820.KS": _p("Communication Services", "Entertainment"),
    "036570.KS": _p("Communication Services", "Electronic Gaming"),
    "323410.KS": _p("Financial Services", "Banks"),
    "009150.KS": _p("Technology", "Electronic Components"),
    "018260.KS": _p("Technology", "IT Services"),
    "033780.KS": _p("Consumer Staples", "Tobacco"),
    "377300.KS": _p("Financial Services", "Fintech"),
    "086790.KS": _p("Financial Services", "Banks"),
    "010130.KS": _p("Basic Materials", "Industrial Metals"),
    "096770.KS": _p("Energy", "Oil & Gas Refining"),
    "003550.KS": _p("Industrials", "Conglomerates"),
    "042660.KS": _p("Industrials", "Shipbuilding"),
    "009540.KS": _p("Industrials", "Shipbuilding"),
    "329180.KS": _p("Industrials", "Heavy Machinery"),
    "009830.KS": _p("Basic Materials", "Chemicals"),
    "034730.KS": _p("Energy", "Oil & Gas Integrated"),
    "402340.KS": _p("Technology", "Investment Holdings"),
    "316140.KS": _p("Financial Services", "Banks"),
    "015760.KS": _p("Utilities", "Electric Utilities"),
    "000810.KS": _p("Financial Services", "Insurance"),
    "138040.KS": _p("Financial Services", "Insurance"),
    "251270.KS": _p("Communication Services", "Electronic Gaming"),
    "263750.KS": _p("Communication Services", "Electronic Gaming"),
    "097950.KS": _p("Consumer Staples", "Food Products"),
    "090430.KS": _p("Consumer Staples", "Personal Products"),
    "051900.KS": _p("Consumer Staples", "Personal Products"),
    "161390.KS": _p("Consumer Cyclical", "Tires & Rubber"),
    "326030.KS": _p("Healthcare", "Pharmaceuticals"),
    "247540.KS": _p("Industrials", "Battery Materials"),
    "086520.KS": _p("Basic Materials", "Chemicals"),
    "022100.KS": _p("Technology", "IT Services"),
    "010140.KS": _p("Industrials", "Shipbuilding"),
    "000720.KS": _p("Industrials", "Construction & Engineering"),
    "003490.KS": _p("Industrials", "Airlines"),
    "011070.KS": _p("Technology", "Electronic Components"),
    "004020.KS": _p("Basic Materials", "Steel"),
    "024110.KS": _p("Financial Services", "Banks"),
    "006800.KS": _p("Financial Services", "Capital Markets"),
    "071050.KS": _p("Financial Services", "Capital Markets"),
    "285130.KS": _p("Basic Materials", "Chemicals"),
    "241560.KS": _p("Industrials", "Heavy Machinery"),
    "035760.KS": _p("Communication Services", "Entertainment"),
    "088350.KS": _p("Financial Services", "Insurance"),
    "034220.KS": _p("Technology", "Electronic Components"),
    "086280.KS": _p("Industrials", "Logistics"),
    "010950.KS": _p("Energy", "Oil & Gas Refining"),
    "016360.KS": _p("Financial Services", "Capital Markets"),
    "042700.KS": _p("Technology", "Semiconductor Equipment"),
    "005830.KS": _p("Financial Services", "Insurance"),
    "005940.KS": _p("Financial Services", "Capital Markets"),
    "021240.KS": _p("Consumer Cyclical", "Home Furnishings"),
    "028300.KS": _p("Healthcare", "Biotechnology"),
    "001570.KS": _p("Basic Materials", "Chemicals"),
    "454910.KS": _p("Industrials", "Industrial Machinery"),
    "058470.KS": _p("Technology", "Electronic Components"),
    "277810.KS": _p("Industrials", "Industrial Machinery"),
    "010120.KS": _p("Industrials", "Electrical Equipment"),
    "267260.KS": _p("Industrials", "Electrical Equipment"),
    "051600.KS": _p("Utilities", "Electric Utilities"),
    "000100.KS": _p("Healthcare", "Pharmaceuticals"),
    "006280.KS": _p("Healthcare", "Pharmaceuticals"),
    "128940.KS": _p("Healthcare", "Pharmaceuticals"),
    "302440.KS": _p("Healthcare", "Biotechnology"),
}

# US listings — aligns with common Yahoo / GICS-style labels
_US: dict[str, tuple[str, str]] = {
    "AAPL": _p("Technology", "Consumer Electronics"),
    "MSFT": _p("Technology", "Software"),
    "GOOGL": _p("Communication Services", "Internet Content"),
    "AMZN": _p("Consumer Cyclical", "E-commerce"),
    "NVDA": _p("Technology", "Semiconductors"),
    "META": _p("Communication Services", "Social Media"),
    "TSLA": _p("Consumer Cyclical", "Auto Manufacturers"),
    "BRK-B": _p("Financial Services", "Insurance"),
    "LLY": _p("Healthcare", "Pharmaceuticals"),
    "V": _p("Financial Services", "Payment Processing"),
    "JPM": _p("Financial Services", "Banks"),
    "UNH": _p("Healthcare", "Managed Care"),
    "XOM": _p("Energy", "Oil & Gas Integrated"),
    "MA": _p("Financial Services", "Payment Processing"),
    "JNJ": _p("Healthcare", "Pharmaceuticals"),
    "PG": _p("Consumer Staples", "Household Products"),
    "AVGO": _p("Technology", "Semiconductors"),
    "HD": _p("Consumer Cyclical", "Home Improvement Retail"),
    "COST": _p("Consumer Defensive", "Discount Stores"),
    "MRK": _p("Healthcare", "Pharmaceuticals"),
    "ABBV": _p("Healthcare", "Pharmaceuticals"),
    "CRM": _p("Technology", "Software"),
    "AMD": _p("Technology", "Semiconductors"),
    "NFLX": _p("Communication Services", "Entertainment"),
    "KO": _p("Consumer Staples", "Beverages"),
    "PEP": _p("Consumer Staples", "Beverages"),
    "TMO": _p("Healthcare", "Life Sciences Tools"),
    "ADBE": _p("Technology", "Software"),
    "WMT": _p("Consumer Defensive", "Discount Stores"),
    "ORCL": _p("Technology", "Software"),
    "DIS": _p("Communication Services", "Entertainment"),
    "BA": _p("Industrials", "Aerospace & Defense"),
    "INTC": _p("Technology", "Semiconductors"),
    "QCOM": _p("Technology", "Semiconductors"),
    "UBER": _p("Technology", "Software / Mobility"),
    "IBM": _p("Technology", "IT Services"),
    "CSCO": _p("Technology", "Communications Equipment"),
    "ACN": _p("Technology", "IT Services"),
    "TXN": _p("Technology", "Semiconductors"),
    "NOW": _p("Technology", "Software"),
    "ISRG": _p("Healthcare", "Medical Devices"),
    "AMGN": _p("Healthcare", "Biotechnology"),
    "GS": _p("Financial Services", "Capital Markets"),
    "MS": _p("Financial Services", "Capital Markets"),
    "BLK": _p("Financial Services", "Asset Management"),
    "SPGI": _p("Financial Services", "Financial Data"),
    "AXP": _p("Financial Services", "Consumer Finance"),
    "PYPL": _p("Financial Services", "Fintech"),
    "BKNG": _p("Consumer Cyclical", "Travel Booking"),
    "GILD": _p("Healthcare", "Biotechnology"),
    "MDLZ": _p("Consumer Staples", "Packaged Foods"),
    "SBUX": _p("Consumer Cyclical", "Restaurants"),
    "PFE": _p("Healthcare", "Pharmaceuticals"),
    "T": _p("Communication Services", "Telecom"),
    "VZ": _p("Communication Services", "Telecom"),
    "CVX": _p("Energy", "Oil & Gas Integrated"),
    "COP": _p("Energy", "Oil & Gas E&P"),
    "NEE": _p("Utilities", "Regulated Electric"),
    "LOW": _p("Consumer Cyclical", "Home Improvement Retail"),
    "UNP": _p("Industrials", "Railroads"),
    "CAT": _p("Industrials", "Heavy Machinery"),
    "DE": _p("Industrials", "Heavy Machinery"),
    "RTX": _p("Industrials", "Aerospace & Defense"),
    "HON": _p("Industrials", "Conglomerates"),
    "LMT": _p("Industrials", "Aerospace & Defense"),
    "GE": _p("Industrials", "Aerospace & Defense"),
    "MMM": _p("Industrials", "Conglomerates"),
    "ADP": _p("Technology", "HR & Payroll Software"),
    "FIS": _p("Technology", "Financial Software"),
    "LRCX": _p("Technology", "Semiconductor Equipment"),
    "KLAC": _p("Technology", "Semiconductor Equipment"),
    "AMAT": _p("Technology", "Semiconductor Equipment"),
    "MU": _p("Technology", "Semiconductors"),
    "PANW": _p("Technology", "Cybersecurity"),
    "SNPS": _p("Technology", "Software"),
    "CDNS": _p("Technology", "Software"),
    "MRVL": _p("Technology", "Semiconductors"),
    "CRWD": _p("Technology", "Cybersecurity"),
    "ZS": _p("Technology", "Cybersecurity"),
    "SNOW": _p("Technology", "Software"),
    "DDOG": _p("Technology", "Software"),
    "NET": _p("Technology", "Software"),
    "SQ": _p("Financial Services", "Fintech"),
    "SHOP": _p("Technology", "E-commerce Software"),
    "COIN": _p("Financial Services", "Capital Markets"),
    "RIVN": _p("Consumer Cyclical", "Auto Manufacturers"),
    "LCID": _p("Consumer Cyclical", "Auto Manufacturers"),
    "NKE": _p("Consumer Cyclical", "Footwear & Apparel"),
    "ABNB": _p("Consumer Cyclical", "Travel"),
    "SPOT": _p("Communication Services", "Entertainment"),
    "SNAP": _p("Communication Services", "Social Media"),
    "RBLX": _p("Communication Services", "Electronic Gaming"),
    "PLTR": _p("Technology", "Software"),
    "ARM": _p("Technology", "Semiconductors"),
    "SMCI": _p("Technology", "Computer Hardware"),
    "MSTR": _p("Technology", "Software"),
    "DELL": _p("Technology", "Computer Hardware"),
    "HPE": _p("Technology", "Computer Hardware"),
    "ROKU": _p("Communication Services", "Entertainment"),
}

STATIC_FUNDAMENTALS: dict[str, tuple[str, str]] = {**_KR, **_US}
